In [1]:
import pandas as pd
import numpy as np

In [2]:
#creating an arra
data = np.array([[1,3],[1,5],[9,6]])

In [3]:
#creating a dataframe
df = pd.DataFrame(data, index= ["row1" , "row 2","row 3"],columns=["col1" , "col2"])

In [4]:
df

       col1  col2
row1      1     3
row 2     1     5
row 3     9     6

Creating dataframe without array

In [5]:
data = [[1,3],[1,5],[9,6]]

In [6]:
#creating dataframe
df = pd.DataFrame(data, index= ["row1" , "row 2","row 3"],columns=["col1" , "col2"])

In [7]:
#showing the dataframe
df

       col1  col2
row1      1     3
row 2     1     5
row 3     9     6

Creating a dataframe from a dictionary

In [8]:
division = ["ঢাকা","চট্টগ্রাম","রাজশাহী","রংপুর","খুলনা","ময়মনসিংহ","সিলেট","বরিশাল"]
populations= [44183580,33345567,20353119,17610856,17416093,12222255,11070244,9325420]

In [9]:
#Making the dictionary
dict_division = {"Division": division , "Populatios": populations}

In [10]:
df =pd.DataFrame(dict_division)

In [11]:
df

    Division  Populatios
0       ঢাকা    44183580
1  চট্টগ্রাম    33345567
2    রাজশাহী    20353119
3      রংপুর    17610856
4      খুলনা    17416093
5  ময়মনসিংহ    12222255
6      সিলেট    11070244
7     বরিশাল     9325420

Creating a DataFrame for a csv file

In [12]:
#reading the csv file
df_employee = pd.read_csv("e:\employees.csv")

<>:2: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
<>:2: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
C:\Users\User\AppData\Local\Temp\ipykernel_21812\4201566151.py:2: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
  df_employee = pd.read_csv("e:\employees.csv")

In [13]:

df_employee

,id,name,age,gender,city,department,salary,experience_years,join_date,rating,email
0,1,Ben,38.0,Male,Kathmandu,Engineering,85500.0,4,2017-10-08,NaN,ben1@example.com
1,2,Priya,47.0,Female,Kathmandu,Finance,100100.0,27,2021-04-15,3.0,priya2@example.com
2,3,Nabil,46.0,Male,Delhi,Engineering,96500.0,25,2023-09-19,4.0,nabil3@example.com
3,4,Iris,39.0,Female,Kathmandu,Marketing,42100.0,3,2015-05-07,3.0,iris4@example.com
4,5,Iris,54.0,Female,Dhaka,HR,104300.0,23,2015-01-20,NaN,iris5@example.com
...,...,...,...,...,...,...,...,...,...,...,...
119,120,Cara,45.0,Female,Dhaka,Marketing,NaN,27,2018-12-12,4.0,cara120@example.com
120,96,Farid,32.0,Female,Karachi,Engineering,52800.0,25,2024-01-06,4.0,farid96@example.com
121,55,Jon,NaN,Female,Dhaka,HR,79800.0,25,2022-03-07,1.0,jon55@example.com
122,60,Nabil,41.0,Male,Karachi,Sales,55900.0,25,2020-11-27,NaN,nabil60@example.com
123,118,Cara,38.0,Female,Dhaka,Marketing,74300.0,5,2021-01-30,4.0,cara118@example.com

In [14]:
df_employee.head()

,id,name,age,gender,city,department,salary,experience_years,join_date,rating,email
0,1,Ben,38.0,Male,Kathmandu,Engineering,85500.0,4,2017-10-08,NaN,ben1@example.com
1,2,Priya,47.0,Female,Kathmandu,Finance,100100.0,27,2021-04-15,3.0,priya2@example.com
2,3,Nabil,46.0,Male,Delhi,Engineering,96500.0,25,2023-09-19,4.0,nabil3@example.com
3,4,Iris,39.0,Female,Kathmandu,Marketing,42100.0,3,2015-05-07,3.0,iris4@example.com
4,5,Iris,54.0,Female,Dhaka,HR,104300.0,23,2015-01-20,NaN,iris5@example.com

In [15]:
df_employee.tail()

,id,name,age,gender,city,department,salary,experience_years,join_date,rating,email
119,120,Cara,45.0,Female,Dhaka,Marketing,NaN,27,2018-12-12,4.0,cara120@example.com
120,96,Farid,32.0,Female,Karachi,Engineering,52800.0,25,2024-01-06,4.0,farid96@example.com
121,55,Jon,NaN,Female,Dhaka,HR,79800.0,25,2022-03-07,1.0,jon55@example.com
122,60,Nabil,41.0,Male,Karachi,Sales,55900.0,25,2020-11-27,NaN,nabil60@example.com
123,118,Cara,38.0,Female,Dhaka,Marketing,74300.0,5,2021-01-30,4.0,cara118@example.com

In [16]:
df_employee.head(50)

,id,name,age,gender,city,department,salary,experience_years,join_date,rating,email
0,1,Ben,38.0,Male,Kathmandu,Engineering,85500.0,4,2017-10-08,NaN,ben1@example.com
1,2,Priya,47.0,Female,Kathmandu,Finance,100100.0,27,2021-04-15,3.0,priya2@example.com
2,3,Nabil,46.0,Male,Delhi,Engineering,96500.0,25,2023-09-19,4.0,nabil3@example.com
3,4,Iris,39.0,Female,Kathmandu,Marketing,42100.0,3,2015-05-07,3.0,iris4@example.com
4,5,Iris,54.0,Female,Dhaka,HR,104300.0,23,2015-01-20,NaN,iris5@example.com
5,6,Sara,43.0,Male,Karachi,Engineering,78200.0,3,2015-01-20,3.0,sara6@example.com
6,7,Ben,25.0,Female,Mumbai,Engineering,59100.0,21,2016-07-01,4.0,ben7@example.com
7,8,Nabil,51.0,Male,Delhi,HR,76300.0,2,2015-06-30,3.0,nabil8@example.com
8,9,Esha,43.0,Female,NaN,Marketing,117000.0,14,2022-11-09,4.0,esha9@example.com
9,10,Ben,46.0,Male,Colombo,Marketing,107200.0,19,2020-10-21,4.0,ben10@example.com
10,11,Kavya,43.0,Male,NaN,Finance,105000.0,21,2024-05-23,4.0,kavya11@example.com
11,12,Uma,43.0,Male,Karachi,Finance,71700.0,12,2022-09-06,4.0,uma12@example.com
12,13,Omar,25.0,Male,Mumbai,Marketing,NaN,27,2024-03-25,4.0,omar13@example.com
13,14,Priya,43.0,Male,Mumbai,Marketing,64700.0,23,2017-04-14,3.0,priya14@example.com
14,15,Omar,52.0,Female,Kathmandu,Engineering,91800.0,6,2017-10-04,NaN,omar15@example.com
15,16,Priya,33.0,Male,Dhaka,HR,87600.0,20,2023-02-20,4.0,priya16@example.com
16,17,Kavya,44.0,Female,Colombo,Sales,52500.0,21,2017-05-07,3.0,kavya17@example.com
17,18,Cara,23.0,Male,Colombo,Engineering,54000.0,10,2015-07-20,4.0,cara18@example.com
18,19,Rafi,35.0,Male,Mumbai,Finance,35500.0,22,2021-05-30,3.0,rafi19@example.com
19,20,Jon,38.0,Female,Delhi,HR,42600.0,26,2022-09-04,4.0,jon20@example.com
20,21,Kavya,59.0,Female,Dhaka,Sales,69000.0,24,2024-04-11,4.0,kavya21@example.com
21,22,Hasan,30.0,Male,Kathmandu,Marketing,73000.0,22,2023-11-22,5.0,hasan22@example.com
22,23,Dev,32.0,Male,Kathmandu,Finance,44900.0,19,2016-02-25,5.0,dev23@example.com
23,24,Tariq,37.0,Female,Delhi,Finance,67500.0,8,2022-05-26,4.0,tariq24@example.com
24,25,Priya,59.0,Female,Dhaka,Engineering,84400.0,23,2023-02-09,4.0,priya25@example.com
25,26,Maya,54.0,Female,Dhaka,HR,50900.0,10,2021-09-09,4.0,maya26@example.com
26,27,Iris,23.0,Male,Dhaka,HR,60400.0,15,2022-11-09,3.0,iris27@example.com
27,28,Rafi,30.0,Male,Colombo,Engineering,63100.0,9,2023-01-11,5.0,rafi28@example.com
28,29,Kavya,53.0,Female,Kathmandu,Engineering,75500.0,9,2019-04-12,4.0,kavya29@example.com
29,30,Iris,24.0,Female,Dhaka,Engineering,63000.0,4,2015-05-21,2.0,iris30@example.com
30,31,Jon,54.0,Male,Colombo,Finance,96300.0,28,2019-05-16,2.0,jon31@example.com
31,32,Esha,32.0,Male,Delhi,Marketing,59500.0,4,2016-12-07,5.0,esha32@example.com
32,33,Ben,56.0,Male,Mumbai,Finance,69000.0,2,2016-02-03,2.0,ben33@example.com
33,34,Liam,33.0,Female,Karachi,Finance,64200.0,28,2016-03-13,3.0,liam34@example.com
34,35,Sara,38.0,Male,Colombo,Finance,46500.0,16,2021-09-06,NaN,sara35@example.com
35,36,Ben,47.0,Male,Kathmandu,Sales,91700.0,13,2019-11-01,3.0,ben36@example.com
36,37,Sara,26.0,Male,Dhaka,Finance,51200.0,22,2020-03-04,3.0,sara37@example.com
37,38,Rafi,43.0,Female,Delhi,Sales,56700.0,11,2022-02-21,4.0,rafi38@example.com
38,39,Farid,41.0,Male,Delhi,HR,101300.0,3,2020-04-02,1.0,farid39@example.com
39,40,Maya,51.0,Male,Delhi,HR,115400.0,21,2021-01-14,NaN,maya40@example.com
40,41,Dev,59.0,Male,Kathmandu,Engineering,90400.0,5,2015-10-29,5.0,dev41@example.com
41,42,Priya,47.0,Male,Colombo,Sales,112500.0,16,2023-02-26,3.0,priya42@example.com
42,43,Omar,37.0,Female,Delhi,Sales,106900.0,28,2019-04-20,3.0,omar43@example.com
43,44,Hasan,37.0,Male,Kathmandu,Finance,73300.0,28,2016-06-27,4.0,hasan44@example.com
44,45,Ben,37.0,Male,Mumbai,Engineering,99300.0,10,2022-10-17,2.0,ben45@example.com
45,46,Uma,52.0,Female,Karachi,Engineering,59600.0,23,2022-01-15,3.0,uma46@example.com
46,47,Iris,34.0,Male,Mumbai,Finance,71400.0,18,2015-07-05,5.0,iris47@example.com
47,48,Sara,28.0,Female,NaN,Sales,78200.0,14,2016-11-06,5.0,sara48@example.com
48,49,Nabil,34.0,Female,Kathmandu,Finance,116400.0,4,2015-02-25,4.0,nabil49@example.com
49,50,Priya,22.0,Male,Dhaka,Finance,106400.0,11,2017-08-05,3.0,priya50@example.com

In [17]:
df_employee.shape

(124, 11)

In [21]:
pd.set_option("display.max_rows", 124)
df_employee

,id,name,age,gender,city,department,salary,experience_years,join_date,rating,email
0,1,Ben,38.0,Male,Kathmandu,Engineering,85500.0,4,2017-10-08,NaN,ben1@example.com
1,2,Priya,47.0,Female,Kathmandu,Finance,100100.0,27,2021-04-15,3.0,priya2@example.com
2,3,Nabil,46.0,Male,Delhi,Engineering,96500.0,25,2023-09-19,4.0,nabil3@example.com
3,4,Iris,39.0,Female,Kathmandu,Marketing,42100.0,3,2015-05-07,3.0,iris4@example.com
4,5,Iris,54.0,Female,Dhaka,HR,104300.0,23,2015-01-20,NaN,iris5@example.com
5,6,Sara,43.0,Male,Karachi,Engineering,78200.0,3,2015-01-20,3.0,sara6@example.com
6,7,Ben,25.0,Female,Mumbai,Engineering,59100.0,21,2016-07-01,4.0,ben7@example.com
7,8,Nabil,51.0,Male,Delhi,HR,76300.0,2,2015-06-30,3.0,nabil8@example.com
8,9,Esha,43.0,Female,NaN,Marketing,117000.0,14,2022-11-09,4.0,esha9@example.com
9,10,Ben,46.0,Male,Colombo,Marketing,107200.0,19,2020-10-21,4.0,ben10@example.com
10,11,Kavya,43.0,Male,NaN,Finance,105000.0,21,2024-05-23,4.0,kavya11@example.com
11,12,Uma,43.0,Male,Karachi,Finance,71700.0,12,2022-09-06,4.0,uma12@example.com
12,13,Omar,25.0,Male,Mumbai,Marketing,NaN,27,2024-03-25,4.0,omar13@example.com
13,14,Priya,43.0,Male,Mumbai,Marketing,64700.0,23,2017-04-14,3.0,priya14@example.com
14,15,Omar,52.0,Female,Kathmandu,Engineering,91800.0,6,2017-10-04,NaN,omar15@example.com
15,16,Priya,33.0,Male,Dhaka,HR,87600.0,20,2023-02-20,4.0,priya16@example.com
16,17,Kavya,44.0,Female,Colombo,Sales,52500.0,21,2017-05-07,3.0,kavya17@example.com
17,18,Cara,23.0,Male,Colombo,Engineering,54000.0,10,2015-07-20,4.0,cara18@example.com
18,19,Rafi,35.0,Male,Mumbai,Finance,35500.0,22,2021-05-30,3.0,rafi19@example.com
19,20,Jon,38.0,Female,Delhi,HR,42600.0,26,2022-09-04,4.0,jon20@example.com
20,21,Kavya,59.0,Female,Dhaka,Sales,69000.0,24,2024-04-11,4.0,kavya21@example.com
21,22,Hasan,30.0,Male,Kathmandu,Marketing,73000.0,22,2023-11-22,5.0,hasan22@example.com
22,23,Dev,32.0,Male,Kathmandu,Finance,44900.0,19,2016-02-25,5.0,dev23@example.com
23,24,Tariq,37.0,Female,Delhi,Finance,67500.0,8,2022-05-26,4.0,tariq24@example.com
24,25,Priya,59.0,Female,Dhaka,Engineering,84400.0,23,2023-02-09,4.0,priya25@example.com
25,26,Maya,54.0,Female,Dhaka,HR,50900.0,10,2021-09-09,4.0,maya26@example.com
26,27,Iris,23.0,Male,Dhaka,HR,60400.0,15,2022-11-09,3.0,iris27@example.com
27,28,Rafi,30.0,Male,Colombo,Engineering,63100.0,9,2023-01-11,5.0,rafi28@example.com
28,29,Kavya,53.0,Female,Kathmandu,Engineering,75500.0,9,2019-04-12,4.0,kavya29@example.com
29,30,Iris,24.0,Female,Dhaka,Engineering,63000.0,4,2015-05-21,2.0,iris30@example.com
30,31,Jon,54.0,Male,Colombo,Finance,96300.0,28,2019-05-16,2.0,jon31@example.com
31,32,Esha,32.0,Male,Delhi,Marketing,59500.0,4,2016-12-07,5.0,esha32@example.com
32,33,Ben,56.0,Male,Mumbai,Finance,69000.0,2,2016-02-03,2.0,ben33@example.com
33,34,Liam,33.0,Female,Karachi,Finance,64200.0,28,2016-03-13,3.0,liam34@example.com
34,35,Sara,38.0,Male,Colombo,Finance,46500.0,16,2021-09-06,NaN,sara35@example.com
35,36,Ben,47.0,Male,Kathmandu,Sales,91700.0,13,2019-11-01,3.0,ben36@example.com
36,37,Sara,26.0,Male,Dhaka,Finance,51200.0,22,2020-03-04,3.0,sara37@example.com
37,38,Rafi,43.0,Female,Delhi,Sales,56700.0,11,2022-02-21,4.0,rafi38@example.com
38,39,Farid,41.0,Male,Delhi,HR,101300.0,3,2020-04-02,1.0,farid39@example.com
39,40,Maya,51.0,Male,Delhi,HR,115400.0,21,2021-01-14,NaN,maya40@example.com
40,41,Dev,59.0,Male,Kathmandu,Engineering,90400.0,5,2015-10-29,5.0,dev41@example.com
41,42,Priya,47.0,Male,Colombo,Sales,112500.0,16,2023-02-26,3.0,priya42@example.com
42,43,Omar,37.0,Female,Delhi,Sales,106900.0,28,2019-04-20,3.0,omar43@example.com
43,44,Hasan,37.0,Male,Kathmandu,Finance,73300.0,28,2016-06-27,4.0,hasan44@example.com
44,45,Ben,37.0,Male,Mumbai,Engineering,99300.0,10,2022-10-17,2.0,ben45@example.com
45,46,Uma,52.0,Female,Karachi,Engineering,59600.0,23,2022-01-15,3.0,uma46@example.com
46,47,Iris,34.0,Male,Mumbai,Finance,71400.0,18,2015-07-05,5.0,iris47@example.com
47,48,Sara,28.0,Female,NaN,Sales,78200.0,14,2016-11-06,5.0,sara48@example.com
48,49,Nabil,34.0,Female,Kathmandu,Finance,116400.0,4,2015-02-25,4.0,nabil49@example.com
49,50,Priya,22.0,Male,Dhaka,Finance,106400.0,11,2017-08-05,3.0,priya50@example.com
50,51,Priya,26.0,Female,Delhi,HR,NaN,19,2015-12-16,4.0,priya51@example.com
51,52,Dev,25.0,Male,Delhi,Sales,88700.0,29,2021-10-20,4.0,dev52@example.com
52,53,Hasan,51.0,Female,Delhi,Sales,48200.0,0,2020-01-03,3.0,hasan53@example.com
53,54,Jon,49.0,Male,Dhaka,Engineering,102400.0,21,2024-05-23,4.0,jon54@example.com
54,55,Jon,NaN,Female,Dhaka,HR,79800.0,25,2022-03-07,1.0,jon55@example.com
55,56,Ana,39.0,Female,Colombo,Sales,77900.0,28,2020-11-10,3.0,ana56@example.com
56,57,Kavya,49.0,Female,Kathmandu,HR,NaN,12,2019-11-18,4.0,kavya57@example.com
57,58,Dev,28.0,Male,Dhaka,Sales,87000.0,3,2015-07-10,3.0,dev58@example.com
58,59,Omar,56.0,Male,Delhi,HR,36500.0,8,2015-09-03,3.0,omar59@example.com
59,60,Nabil,41.0,Male,Karachi,Sales,55900.0,25,2020-11-27,NaN,nabil60@example.com
60,61,Tariq,57.0,Male,Kathmandu,Marketing,45900.0,26,2015-01-16,5.0,tariq61@example.com
61,62,Omar,NaN,Female,Colombo,Sales,96100.0,19,2015-05-29,4.0,omar62@example.com
62,63,Hasan,40.0,Male,Colombo,Sales,33200.0,3,2017-02-05,5.0,hasan63@example.com
63,64,Uma,48.0,Female,Karachi,Sales,48200.0,3,2023-06-22,5.0,uma64@example.com
64,65,Iris,40.0,Female,Mumbai,Finance,NaN,14,2019-05-26,2.0,iris65@example.com
65,66,Gita,38.0,Male,Delhi,Sales,92500.0,17,2021-10-19,3.0,gita66@example.com
66,67,Tariq,28.0,Male,Kathmandu,HR,75300.0,0,2018-12-11,3.0,tariq67@example.com
67,68,Hasan,36.0,Female,Colombo,HR,107500.0,20,2016-08-28,2.0,hasan68@example.com
68,69,Ben,31.0,Male,Dhaka,HR,112700.0,16,2018-07-23,4.0,ben69@example.com
69,70,Jon,33.0,Male,Colombo,Marketing,41900.0,0,2015-11-18,3.0,jon70@example.com
70,71,Priya,47.0,Female,Dhaka,Finance,115700.0,2,2022-05-19,4.0,priya71@example.com
71,72,Dev,45.0,Female,Colombo,Engineering,85300.0,13,2016-10-04,NaN,dev72@example.com
72,73,Jon,45.0,Male,Colombo,Finance,87300.0,21,2018-08-10,3.0,jon73@example.com
73,74,Cara,35.0,Male,Dhaka,Engineering,38600.0,24,2024-05-23,5.0,cara74@example.com
74,75,Nabil,58.0,Male,Mumbai,Finance,86000.0,12,2020-09-02,1.0,nabil75@example.com
75,76,Jon,25.0,Female,Dhaka,HR,NaN,8,2019-05-24,3.0,jon76@example.com
76,77,Gita,NaN,Female,Karachi,Marketing,82300.0,29,2020-03-15,3.0,gita77@example.com
77,78,Esha,26.0,Female,NaN,Finance,NaN,13,2022-07-07,4.0,esha78@example.com
78,79,Liam,34.0,Female,Dhaka,Marketing,77100.0,9,2017-06-09,4.0,liam79@example.com
79,80,Nabil,58.0,Female,Mumbai,Finance,114200.0,13,2021-02-05,4.0,nabil80@example.com
80,81,Tariq,35.0,Male,Kathmandu,HR,95100.0,0,2023-05-13,2.0,tariq81@example.com
81,82,Iris,56.0,Male,Delhi,Sales,42400.0,9,2020-06-26,3.0,iris82@example.com
82,83,Dev,40.0,Female,Dhaka,HR,NaN,15,2019-04-12,5.0,dev83@example.com
83,84,Rafi,48.0,Female,Mumbai,Sales,116300.0,27,2016-05-22,4.0,rafi84@example.com
84,85,Maya,39.0,Female,Karachi,Finance,45200.0,22,2017-05-19,4.0,maya85@example.com
85,86,Omar,32.0,Male,Karachi,Engineering,102100.0,23,2024-01-25,4.0,omar86@example.com
86,87,Ben,NaN,Male,Delhi,Engineering,66600.0,16,2020-03-09,4.0,ben87@example.com
87,88,Gita,58.0,Male,Kathmandu,Engineering,83400.0,3,2017-11-20,2.0,gita88@example.com
88,89,Priya,NaN,Male,Karachi,Marketing,70100.0,11,2019-01-04,3.0,priya89@example.com
89,90,Rafi,51.0,Female,Delhi,HR,100400.0,29,2020-07-16,4.0,rafi90@example.com
90,91,Iris,31.0,Female,Kathmandu,Finance,119700.0,1,2020-02-25,3.0,iris91@example.com
91,92,Rafi,49.0,Male,Kathmandu,HR,101600.0,26,2021-09-15,5.0,rafi92@example.com
92,93,Rafi,51.0,Male,Mumbai,Engineering,NaN,20,2017-06-20,NaN,rafi93@example.com
93,94,Hasan,39.0,Female,NaN,Sales,115100.0,8,2021-03-22,4.0,hasan94@example.com
94,95,Sara,50.0,Male,Karachi,Sales,38100.0,23,2019-03-30,5.0,sara95@example.com
95,96,Farid,32.0,Female,Karachi,Engineering,52800.0,25,2024-01-06,4.0,farid96@example.com
96,97,Esha,25.0,Female,Dhaka,Finance,95000.0,1,2016-07-06,5.0,esha97@example.com
97,98,Nabil,25.0,Male,Karachi,HR,83100.0,3,2016-06-03,4.0,nabil98@example.com
98,99,Maya,38.0,Male,Kathmandu,Finance,34500.0,19,2019-06-04,5.0,maya99@example.com
99,100,Cara,NaN,Female,Dhaka,Sales,38600.0,29,2019-11-15,3.0,cara100@example.com
100,101,Rafi,26.0,Female,Colombo,Sales,76800.0,0,2021-08-15,4.0,rafi101@example.com
101,102,Dev,39.0,Male,Dhaka,Finance,85500.0,19,2018-11-15,4.0,dev102@example.com
102,103,Rafi,48.0,Female,Colombo,Sales,45100.0,4,2023-10-04,2.0,rafi103@example.com
103,104,Ana,29.0,Female,Mumbai,Sales,45400.0,19,2019-07-18,3.0,ana104@example.com
104,105,Priya,49.0,Female,Dhaka,HR,41600.0,18,2016-03-28,5.0,priya105@example.com
105,106,Priya,33.0,Male,Kathmandu,Finance,80800.0,2,2016-02-22,4.0,priya106@example.com
106,107,Priya,NaN,Female,Dhaka,Marketing,30700.0,20,2024-04-29,3.0,priya107@example.com
107,108,Nabil,44.0,Female,Karachi,Sales,81500.0,26,2016-04-14,3.0,nabil108@example.com
108,109,Jon,42.0,Male,Delhi,Finance,72800.0,25,2024-01-31,3.0,jon109@example.com
109,110,Omar,28.0,Male,Kathmandu,Finance,71900.0,0,2017-08-31,1.0,omar110@example.com
110,111,Farid,39.0,Female,Colombo,Finance,91100.0,7,2015-11-23,5.0,farid111@example.com
111,112,Priya,54.0,Male,Colombo,Finance,77000.0,7,2017-12-02,3.0,priya112@example.com
112,113,Liam,22.0,Male,Mumbai,Engineering,95500.0,13,2020-11-21,3.0,liam113@example.com
113,114,Jon,NaN,Male,Mumbai,Finance,NaN,4,2019-02-06,4.0,jon114@example.com
114,115,Kavya,40.0,Female,Karachi,Engineering,112800.0,25,2022-07-12,1.0,kavya115@example.com
115,116,Liam,49.0,Female,Colombo,Finance,101900.0,23,2020-11-08,NaN,liam116@example.com
116,117,Ana,47.0,Male,Kathmandu,HR,76600.0,24,2018-11-03,4.0,ana117@example.com
117,118,Cara,38.0,Female,Dhaka,Marketing,74300.0,5,2021-01-30,4.0,cara118@example.com
118,119,Esha,33.0,Male,Karachi,Marketing,51200.0,0,2024-04-23,5.0,esha119@example.com
119,120,Cara,45.0,Female,Dhaka,Marketing,NaN,27,2018-12-12,4.0,cara120@example.com
120,96,Farid,32.0,Female,Karachi,Engineering,52800.0,25,2024-01-06,4.0,farid96@example.com
121,55,Jon,NaN,Female,Dhaka,HR,79800.0,25,2022-03-07,1.0,jon55@example.com
122,60,Nabil,41.0,Male,Karachi,Sales,55900.0,25,2020-11-27,NaN,nabil60@example.com
123,118,Cara,38.0,Female,Dhaka,Marketing,74300.0,5,2021-01-30,4.0,cara118@example.com